# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input

# Configuração padrão de entrada
input {
  # Opção importante: resolve binds por símbolo ao invés de posição
  resolve_binds_by_sym = true

  # Change speed of keyboard repeat
  repeat_rate = 40
  repeat_delay = 600

  # Start with numlock on by default
  numlock_by_default = true

  # Increase sensitity for mouse/trackpack (default: 0)
  # sensitivity = 0.35

  touchpad {
    # Use natural (inverse) scrolling
    # natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
    # clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.4
  }
}

# Configuração específica para o teclado do notebook (ABNT2 com cedilha)
device {
  name = at-translated-set-2-keyboard
  kb_layout = br
  kb_variant = abnt2
  kb_model = pc105
  kb_options = 
}

# Configuração específica para o Logitech K380 (US)
device {
  name = keyboard-k380-keyboard
  kb_layout = us
  kb_variant = altgr-intl
  kb_model = pc105
  kb_options = 
}

# Scroll faster in the terminal
windowrule = scrolltouchpad 1.5, tag:terminal
